#!/bin/bash

csv_path="worldcities.csv"

rows-for() {
	grep ",$1," $csv_path
}

sum() {
	total=0
	while read n; do
		[ -z "$n" ] && n=0
		total=$(( total + n ))
	done

	echo "$total"
}


count() {
	rows-for "$1" | wc -l
}

total() {
	rows-for "$1" | cut -d, -f8 | sum
}

average() {
	total=$(total "$1")
	count=$(count "$1")
	if [[ $count -eq 0 ]]; then
		echo "0"
		exit 0
	fi
	echo $(( "$total" / "$count" ))
}

if [[ "$#" -lt 2 ]]; then
	echo "Invalid arguments" >&2
	exit 1
fi

operation=$1
country="$2"

case $operation in
	count) count "$country";;
	total) total "$country";;
	average) average "$country";;
	*) echo "Unknown operation: $operation" >&2 ; exit 1 ;;
esac
